### ISSUE TITLE
windows 下有报错

### ISSUE THREAD

**Issue by barretlee** [barretlee/kindleBookMaker#1]
![windows err](http://ww4.sinaimg.cn/large/6d64e151gw1f447cvr9rtj20sh0hajyv.jpg)

http://v2ex.com/t/280089#t17 by [hillw4h](http://v2ex.com/member/hillw4h)

**Comment by barretlee** [comment]
未测试非 Mac 系统，晚上回去探索下原因，感觉应该是 Node 的 child_process 模块在 windows 下使用报错了。

**Comment by laysent** [comment]
在 bin 里的 kindlegen 应该是针对 MAC 系统的版本，所以在 Windows 下运行会报错。如果换成 Windows 下的 kindlegen.exe 的话，我这里试了下就能跑了，且可以生成 .mobi 文件。（测试的系统是 Win 10）

**Comment by barretlee** [comment]
@laysent 多谢多谢，我加下说明~
